export const Strings = {
  appName: '외워줘',
  home: '홈',
  sets: '카드 세트',
  study: '학습',
  stats: '통계',
  settings: '설정',
  todayReview: '오늘의 복습',
  noReviewToday: '오늘 복습할 카드가 없습니다',
  noReviewDesc: '새로운 카드를 추가하거나 학습을 시작해보세요!',
  createSet: '새 세트 만들기',
  editSet: '세트 편집',
  deleteSet: '세트 삭제',
  addCard: '카드 추가',
  editCard: '카드 편집',
  deleteCard: '카드 삭제',
  front: '앞면',
  cardBack: '뒷면',
  frontPlaceholder: '단어, 개념, 질문을 입력하세요',
  backPlaceholder: '뜻, 설명, 답을 입력하세요',
  setName: '세트 이름',
  setNamePlaceholder: '예: 수능 영단어',
  setDesc: '설명 (선택)',
  setDescPlaceholder: '세트에 대한 설명',
  save: '저장',
  cancel: '취소',
  delete: '삭제',
  confirm: '확인',
  back: '뒤로',
  start: '학습 시작',
  reviewNow: '지금 복습',
  totalCards: '전체 카드',
  masteredCards: '완성 카드',
  learningCards: '학습 중',
  newCards: '새 카드',
  dontKnow: '몰라요',
  fuzzy: '헷갈려요',
  know: '알아요',
  perfect: '완벽해요',
  sessionComplete: '학습 완료!',
  cardsStudied: '학습한 카드',
  correctRate: '정답률',
  continueStudy: '이어서 학습',
  backToSet: '세트로 돌아가기',
  streak: '연속 학습',
  days: '일',
  todayGoal: '오늘 목표',
  cards: '장',
  presets: '프리셋',
  presetDesc: '미리 만들어진 카드 세트',
  mysets: '내 세트',
  wrongNotes: '오답 노트',
  wrongNotesDesc: '틀렸던 카드 모음',
  noCards: '카드가 없습니다',
  noCardsDesc: '카드를 추가해서 학습을 시작하세요',
  noSets: '세트가 없습니다',
  noSetsDesc: '새 세트를 만들거나 프리셋을 추가해보세요',
  deleteConfirm: '정말 삭제하시겠습니까?',
  deleteSetConfirm: '세트와 모든 카드가 삭제됩니다.',
  deleteCardConfirm: '이 카드가 삭제됩니다.',
  importExport: '백업/복원',
  export: '내보내기',
  import: '가져오기',
  exportSuccess: '내보내기 완료',
  importSuccess: '가져오기 완료',
  exportFail: '내보내기 실패',
  importFail: '가져오기 실패',
  studyAll: '전체 학습',
  studyNew: '새 카드만',
  studyReview: '복습 카드만',
  addPreset: '프리셋 추가',
  nextReview: '다음 복습',
  today: '오늘',
  tomorrow: '내일',
  inDays: (n: number) => `${n}일 후`,
  levelUp: '레벨 업!',
  level: '레벨',
} as const;
